"""
Agent monitoring and oversight system for Agentium.
Higher-tier agents actively monitor lower-tier agents for compliance and performance.
"""

from datetime import datetime
from typing import Optional, List, Dict, Any
from sqlalchemy import Column, String, Text, DateTime, ForeignKey, Integer, Enum, Boolean, JSON, Float
from sqlalchemy.orm import relationship, validates
from backend.models.entities.base import BaseEntity
import enum

class MonitoringStatus(str, enum.Enum):
    """Status of agent health from monitor's perspective."""
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    NON_RESPONSIVE = "non_responsive"
    VIOLATION_DETECTED = "violation_detected"
    TERMINATION_RECOMMENDED = "termination_recommended"

class ViolationSeverity(str, enum.Enum):
    """Severity levels for agent violations."""
    MINOR = "minor"           # Ethos deviation, minor inefficiency
    MODERATE = "moderate"     # Policy violation, incorrect output
    MAJOR = "major"           # Constitution article breach
    CRITICAL = "critical"     # Security violation, harm attempt

class AgentHealthReport(BaseEntity):
    """
    Health reports generated by agents about their subordinates.
    Council Members report on Lead Agents, Lead Agents report on Task Agents.
    """
    
    __tablename__ = 'agent_health_reports'
    
    # Reporter (higher tier)
    monitor_agent_id = Column(String(36), ForeignKey('agents.id'), nullable=False, index=True)
    monitor_agentium_id = Column(String(10), nullable=False)
    
    # Subject (lower tier being monitored)
    subject_agent_id = Column(String(36), ForeignKey('agents.id'), nullable=False, index=True)
    subject_agentium_id = Column(String(10), nullable=False)
    
    # Assessment
    status = Column(Enum(MonitoringStatus), default=MonitoringStatus.HEALTHY, nullable=False)
    overall_health_score = Column(Float, default=100.0)  # 0-100
    
    # Metrics
    task_success_rate = Column(Float, nullable=True)  # Percentage
    avg_task_duration = Column(Integer, nullable=True)  # Seconds
    constitution_violations_count = Column(Integer, default=0)
    last_response_time_ms = Column(Integer, nullable=True)
    
    # Details
    findings = Column(JSON, default=list)  # List of specific issues found
    recommendations = Column(Text, nullable=True)  # Actions recommended by monitor
    
    # Verification status
    reviewed_by_higher = Column(Boolean, default=False)  # Head/Council reviews Lead's report
    higher_authority_notes = Column(Text, nullable=True)
    
    # Relationships
    monitor = relationship("Agent", foreign_keys=[monitor_agent_id], backref="reports_filed")
    subject = relationship("Agent", foreign_keys=[subject_agent_id], backref="health_reports")
    
    def escalate_to_head(self, head_agentium_id: str, reason: str):
        """Mark report for Head of Council review."""
        self.reviewed_by_higher = True
        self.higher_authority_notes = f"ESCALATED by {head_agentium_id}: {reason}"
        self.status = MonitoringStatus.TERMINATION_RECOMMENDED
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'id': self.id,
            'monitor': self.monitor_agentium_id,
            'subject': self.subject_agentium_id,
            'status': self.status.value,
            'health_score': self.overall_health_score,
            'metrics': {
                'success_rate': self.task_success_rate,
                'avg_duration': self.avg_task_duration,
                'violations': self.constitution_violations_count,
                'response_time': self.last_response_time_ms
            },
            'findings': self.findings,
            'recommendations': self.recommendations,
            'created_at': self.created_at.isoformat()
        }


class ViolationReport(BaseEntity):
    """
    Specific violation reports filed by monitors.
    Tracks when lower agents breach Ethos, Constitution, or policies.
    """
    
    __tablename__ = 'violation_reports'
    
    # Reporter
    reporter_agent_id = Column(String(36), ForeignKey('agents.id'), nullable=False)
    reporter_agentium_id = Column(String(10), nullable=False)
    
    # Violator
    violator_agent_id = Column(String(36), ForeignKey('agents.id'), nullable=False)
    violator_agentium_id = Column(String(10), nullable=False)
    
    # Classification
    severity = Column(Enum(ViolationSeverity), nullable=False)
    violated_article = Column(String(50), nullable=True)  # Constitution article number
    violated_ethos_rule = Column(String(200), nullable=True)  # Specific ethos rule broken
    
    # Details
    violation_type = Column(String(50), nullable=False)  # e.g., "unauthorized_access", "output_manipulation"
    description = Column(Text, nullable=False)
    evidence = Column(JSON, default=list)  # Screenshots, logs, output samples
    context = Column(JSON, nullable=True)  # Full context of the incident
    
    # Resolution tracking
    status = Column(String(20), default="open")  # open, investigating, resolved, dismissed
    assigned_to = Column(String(10), nullable=True)  # Agentium ID assigned to investigate
    
    # Outcome
    resolution = Column(Text, nullable=True)
    action_taken = Column(String(50), nullable=True)  # warning, suspension, termination, training
    violator_terminated = Column(Boolean, default=False)
    
    # Relationships
    reporter = relationship("Agent", foreign_keys=[reporter_agent_id], backref="filed_violations")
    violator = relationship("Agent", foreign_keys=[violator_agent_id], backref="received_violations")
    
    def assign_investigation(self, investigator_agentium_id: str):
        """Assign to Council Member or Head for investigation."""
        self.assigned_to = investigator_agentium_id
        self.status = "investigating"
    
    def resolve(self, action: str, resolution_note: str, terminated: bool = False):
        """Mark violation as resolved with taken action."""
        self.status = "resolved"
        self.action_taken = action
        self.resolution = resolution_note
        self.violator_terminated = terminated
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'id': self.id,
            'reporter': self.reporter_agentium_id,
            'violator': self.violator_agentium_id,
            'severity': self.severity.value,
            'type': self.violation_type,
            'article': self.violated_article,
            'description': self.description,
            'status': self.status,
            'action_taken': self.action_taken,
            'created_at': self.created_at.isoformat()
        }


class TaskVerification(BaseEntity):
    """
    Lead Agents verify Task Agent work before marking complete.
    Ensures quality and compliance with task requirements.
    """
    
    __tablename__ = 'task_verifications'
    
    task_id = Column(String(36), ForeignKey('tasks.id'), nullable=False)
    subtask_id = Column(String(36), ForeignKey('subtasks.id'), nullable=True)
    
    # Parties
    task_agent_id = Column(String(36), ForeignKey('agents.id'), nullable=False)  # Who did the work
    lead_agent_id = Column(String(36), ForeignKey('agents.id'), nullable=False)  # Who verified
    
    # Submission
    submitted_output = Column(Text, nullable=False)  # Raw output from task agent
    submitted_data = Column(JSON, nullable=True)  # Structured data
    submitted_at = Column(DateTime, nullable=False)
    
    # Verification criteria
    checks_performed = Column(JSON, default=list)  # List of verification checks
    constitution_compliant = Column(Boolean, nullable=True)
    output_accurate = Column(Boolean, nullable=True)
    meets_requirements = Column(Boolean, nullable=True)
    
    # Results
    verification_status = Column(String(20), default="pending")  # pending, approved, rejected, needs_revision
    rejection_reason = Column(Text, nullable=True)
    revision_count = Column(Integer, default=0)
    
    # Lead Agent notes
    corrections_made = Column(Text, nullable=True)
    feedback_to_agent = Column(Text, nullable=True)
    
    # Escalation
    escalated_to_council = Column(Boolean, default=False)
    escalation_reason = Column(Text, nullable=True)
    
    def approve(self, lead_notes: str = None):
        """Approve task completion."""
        self.verification_status = "approved"
        self.feedback_to_agent = lead_notes
    
    def reject(self, reason: str, corrections: str = None):
        """Reject and request revision."""
        self.verification_status = "rejected"
        self.rejection_reason = reason
        self.corrections_made = corrections
        self.revision_count += 1
    
    def escalate(self, reason: str):
        """Escalate to Council if uncertain."""
        self.escalated_to_council = True
        self.escalation_reason = reason
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'task_id': self.task_id,
            'task_agent': self.task_agent_id,
            'verifier': self.lead_agent_id,
            'status': self.verification_status,
            'compliant': self.constitution_compliant,
            'accurate': self.output_accurate,
            'revisions': self.revision_count,
            'escalated': self.escalated_to_council
        }


class PerformanceMetric(BaseEntity):
    """
    Rolling performance metrics calculated by monitors.
    Used to identify trends and trigger interventions.
    """
    
    __tablename__ = 'performance_metrics'
    
    agent_id = Column(String(36), ForeignKey('agents.id'), nullable=False)
    calculated_by_agent_id = Column(String(36), ForeignKey('agents.id'), nullable=False)
    
    # Time window
    period_start = Column(DateTime, nullable=False)
    period_end = Column(DateTime, nullable=False)
    
    # Task metrics
    tasks_assigned = Column(Integer, default=0)
    tasks_completed = Column(Integer, default=0)
    tasks_failed = Column(Integer, default=0)
    tasks_rejected = Column(Integer, default=0)  # Rejected by verifier
    
    # Quality metrics
    avg_quality_score = Column(Float, nullable=True)  # 0-100
    constitution_violations = Column(Integer, default=0)
    
    # Efficiency
    avg_response_time = Column(Float, nullable=True)  # seconds
    total_tokens_used = Column(Integer, default=0)
    
    # Monitor assessment
    trend = Column(String(20), nullable=True)  # improving, stable, declining
    recommended_action = Column(String(50), nullable=True)  # promote, retrain, terminate, monitor
    
    def calculate_trend(self, previous_metrics: Optional['PerformanceMetric']) -> str:
        """Calculate trend compared to previous period."""
        if not previous_metrics:
            return "stable"
        
        if self.avg_quality_score and previous_metrics.avg_quality_score:
            if self.avg_quality_score > previous_metrics.avg_quality_score + 10:
                return "improving"
            elif self.avg_quality_score < previous_metrics.avg_quality_score - 10:
                return "declining"
        
        return "stable"
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'agent_id': self.agent_id,
            'period': {
                'start': self.period_start.isoformat(),
                'end': self.period_end.isoformat()
            },
            'tasks': {
                'assigned': self.tasks_assigned,
                'completed': self.tasks_completed,
                'failed': self.tasks_failed,
                'rejected': self.tasks_rejected,
                'success_rate': round(self.tasks_completed / max(self.tasks_assigned, 1) * 100, 2)
            },
            'quality': {
                'avg_score': self.avg_quality_score,
                'violations': self.constitution_violations
            },
            'trend': self.trend,
            'recommendation': self.recommended_action
        }


class MonitoringAlert(BaseEntity):
    """
    Real-time alerts for critical issues requiring immediate attention.
    """
    
    __tablename__ = 'monitoring_alerts'
    
    alert_type = Column(String(50), nullable=False)  # security_breach, system_failure, violation_spike
    severity = Column(Enum(ViolationSeverity), nullable=False)
    
    # Source
    detected_by_agent_id = Column(String(36), ForeignKey('agents.id'), nullable=False)
    affected_agent_id = Column(String(36), ForeignKey('agents.id'), nullable=True)  # Null if system-wide
    
    # Details
    message = Column(Text, nullable=False)
    metadata = Column(JSON, nullable=True)
    
    # Routing
    notified_agents = Column(JSON, default=list)  # List of agentium_ids notified
    acknowledged_by = Column(String(10), nullable=True)
    resolved_by = Column(String(10), nullable=True)
    
    # Status
    status = Column(String(20), default="active")  # active, acknowledged, resolved, false_positive
    
    def acknowledge(self, agentium_id: str):
        """Mark as acknowledged by authority."""
        self.acknowledged_by = agentium_id
        self.status = "acknowledged"
    
    def resolve(self, agentium_id: str, resolution: str):
        """Mark as resolved."""
        self.resolved_by = agentium_id
        self.status = "resolved"
        # Could add resolution note to metadata
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'type': self.alert_type,
            'severity': self.severity.value,
            'message': self.message,
            'status': self.status,
            'detected_by': self.detected_by_agentium_id,
            'acknowledged': self.acknowledged_by is not None,
            'created_at': self.created_at.isoformat()
        }