@echo off
:: ============================================================================
:: Agentium Voice Bridge Bootstrap
:: Auto-generated by docker-compose voice-autoinstall service.
:: Automatically requests UAC elevation — no manual "Run as Administrator" needed.
:: ============================================================================
setlocal EnableDelayedExpansion

set AGENTIUM_DIR=%USERPROFILE%\.agentium
set LOG=%AGENTIUM_DIR%\bootstrap.log

:: REPO_ROOT is baked in by voice-autoinstall.sh — do not edit this line manually
set REPO=AGENTIUM_REPO_ROOT
set SETUP=%REPO%\voice-bridge\setup.ps1

echo [%DATE% %TIME%] Bootstrap started >> "%LOG%" 2>&1

if not exist "%AGENTIUM_DIR%" mkdir "%AGENTIUM_DIR%"

:: Verify setup.ps1 exists before attempting elevation
if not exist "%SETUP%" (
    echo [%DATE% %TIME%] ERROR: setup.ps1 not found at %SETUP% >> "%LOG%"
    echo.
    echo  ERROR: Agentium setup.ps1 was not found.
    echo  Expected: %SETUP%
    echo.
    echo  Please run setup.ps1 manually from your repo:
    echo    powershell -ExecutionPolicy Bypass -File "^<repo^>\voice-bridge\setup.ps1"
    echo.
    pause
    exit /b 1
)

:: Launch setup.ps1 via PowerShell with -Verb runas (triggers UAC prompt automatically).
:: The script itself handles all self-elevation logic.
echo [%DATE% %TIME%] Launching setup.ps1 with elevation request... >> "%LOG%"

powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "Start-Process powershell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File \"%SETUP%\"' -Verb runas -Wait" >> "%LOG%" 2>&1

set EXIT_CODE=%ERRORLEVEL%
echo [%DATE% %TIME%] Bootstrap complete (exit %EXIT_CODE%) >> "%LOG%"
exit /b %EXIT_CODE%